services:
  nextjs:
    container_name: ${PROJECT}_nextjs
    build:
      context: ./nextjs
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      DATABASE_URL: "postgresql://postgres:pwd@db:5432/postgres?search_path=public"

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000

  db:
    container_name: ${PROJECT}_db
    build:
      context: ./db
      dockerfile: dev.Dockerfile
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pwd
    networks:
      - backend

  adminer:
    container_name: ${PROJECT}_adminer
    image: adminer
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend:
    name: ${PROJECT}_frontend
  backend:
    name: ${PROJECT}_backend
